### ISSUE TITLE
`ci` not initialized before use

### ISSUE THREAD

**Issue by rountree** [csiro-coasts/EMS#15]
In `model/hd/momentum/advect.c` beginning with line 6253:

```
6253 void semi_lagrange_u2(geometry_t *window,  /* Processing window      */
...
6277   int cc, c, ci, c2, zm1;
...
6308     nu[c] = nu[ci];
...
```

In the next two for loops `ci` is initialized as follows:
```
6313     ci = window->bine2[cc];
...
6323     ci = window->bine2[cc];
```

I'm guessing that line was inadvertently omitted from the first for loop.  I'll submit a PR copying it there, but the only rationale I have for this is stylistic.

**Comment by frizwi** [comment]
Fixed in latest
