### ISSUE TITLE
Running `shoc -rg auto.prm` fails if DO_ECOLOGY is enabled if the `salt` and `temp` tracers are not predefined in auto.prm

### ISSUE THREAD

**Issue by sharon-tickell** [csiro-coasts/EMS#30]
With the new v1.5.2 release of EMS, and _after_ a workaround is patched in for https://github.com/csiro-coasts/EMS/issues/28,   running `shoc -rg auto.prm`  fails, and the runlog contains an error like:

```
[FATAL ]() density_w: Tracers 'salt' and 'temp' must both be present.
```
This occurs for combinations of BIOFNAME and PROCESSFNAME including:
* BGC3p1 + BGC3p1
* BGC2p0 + BGC2p0
* TASSE1p0 + TASSE1p0
* porewater + porewater_age

I have been about to work around it by including these lines in the `auto.prm` file:
```
NTRACERS             2
TRACER0.name         salt
TRACER0.long_name    Salinity
TRACER0.units        PSU
TRACER0.fill_value   35.0
TRACER0.valid_range  0.0    40.0
TRACER0.advect       1
TRACER0.diffuse      1
TRACER0.diagn        0
TRACER1.name         temp
TRACER1.long_name    Temperature
TRACER1.units        degrees C
TRACER1.fill_value   25.0
TRACER1.valid_range  0.0    40.0
TRACER1.advect       1
TRACER1.diffuse      1
TRACER1.diagn        0
```

I don't believe these lines are causing problems (the `in.tran` file still gets generated with 9 tracers in it), but they didn't used to be necessary, and I suspect that them being needed now is a bug.

**Comment by frizwi** [comment]
Fixed in release 1.5.3

No need to explicitly add salt/temp tracers in auto.prm (i.e. please revert back to the the prev auto.prm)
