### ISSUE TITLE
Two Woverflow warnings (TIDALM boundary condition ignored)

### ISSUE THREAD

**Issue by rountree** [csiro-coasts/EMS#6]
Both copies of boundary.h contain a `struct open_bdrys` that uses `int` members to hold boundary condition flags found in hd_params.h.  An `int` can support 32 distinct flags, and `TIDALM` has been added as the 33rd.  The warning refers to it being forced to zero when stored in a 32-bit `int`.

The most straightforward fix would be to change the types of all variables that could hold boundary conditions to either `long int` or `uint64_t`.  The former is guaranteed to be at least 64 bits on all systems (but can be more), the latter requires intrusive changes to print formatting to be fully portable.

A much quicker fix is to sacrifice one of the existing boundary conditions and replace it with TIDALM.  I don't expect that will be a viable long-term solution, and the ability to have 64 conditions (or at least more than 32) will be useful down the road.

**Comment by frizwi** [comment]
TIDALM not is use
